import type { Metadata } from "next";

export const metadata: Metadata = { title: "Method — Reading the Mencius from First Principles", description: "A six-step method for reading the Mencius through text, problem, premise, reasoning, limits, and present application.", alternates: { canonical: "https://www.mengtzu.com/en/method", languages: { en: "https://www.mengtzu.com/en/method", "zh-Hans": "https://www.mengtzu.com/zh/method" } } };

export default function MethodPage() {
  return <main><header className="masthead"><a className="brand" href="/en"><span className="seal">孟</span><span>mengtzu<small>.com</small></span></a><nav><a href="/en/books">Books</a><a className="active-link" href="/en/method">Method</a><a href="/en/sources">Sources</a><span className="locale-switch"><a href="/zh">简体中文</a><a className="active" href="/en">English</a></span></nav></header>
    <section className="info-hero"><div className="eyebrow">Do not inherit the answer · Rebuild the argument</div><h1>Take it apart.<br/>Then understand it.</h1><p>First-principles reading does not turn an ancient text into a modern slogan. It temporarily sets authority aside and asks which observations, assumptions, and inferences make an argument stand.</p></section>
    <section className="principle-steps"><article><span>01</span><h2>Establish the words</h2><p>Begin with what Mencius actually says. Keep the speaker, audience, context, and canonical location visible.</p></article><article><span>02</span><h2>Recover the problem</h2><p>Separate the surface question from the underlying conflict: profit, order, human nature, or responsibility.</p></article><article><span>03</span><h2>Expose the premise</h2><p>State the assumptions that remain implicit, such as whether compassion is innate or institutions amplify choice.</p></article><article><span>04</span><h2>Inspect the reasoning</h2><p>Trace how the conclusion follows and what work is done by analogy, reversal, reductio, and observation.</p></article><article><span>05</span><h2>Test the boundary</h2><p>Ask under which conditions the principle holds and which counterexamples would make it fail.</p></article><article><span>06</span><h2>Return to the present</h2><p>Do not force an application. Turn the principle into a question that can be observed, debated, and tested today.</p></article></section>
  </main>;
}
